<?php

namespace Eyewitness\Eye\Test\Controllers\DashboardTabs;

use Eyewitness\Eye\Test\TestCase;
use Eyewitness\Eye\Repo\Notifications\History;

class NotificationTabTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->artisan('migrate', ['--database' => 'testbench']);
    }

    public function test_notifications_tab_when_empty()
    {
        History::truncate();

        $response = $this->withSession(['eyewitness:auth' => 1])
                         ->get($this->home.'/dashboard');

        $response->assertStatus(200);
        $response->assertSee('All Eyewitness notifications are displayed here for '.config('eyewitness.days_to_keep_history').' days.');
        $response->assertSee('No outstanding notifications');
        $response->assertSee('If a notification is generated by your application it will appear here');
    }

    public function test_notifications_tab_loads_notifications()
    {
        $history = factory(History::class)->create();

        $response = $this->withSession(['eyewitness:auth' => 1])
                         ->get($this->home.'/dashboard');

        $response->assertStatus(200);
        $response->assertSee('Outstanding notifications');
        $response->assertSee($history->title);
    }
}
